version: '2'
services:

  dev:
    build:
      context: ./
    image: muccg/logspout-logstash:${GIT_BRANCH}

  prod:
    build:
      context: ./
    image: muccg/logspout-logstash:${DOCKER_LOGSPOUT_VERSION}

  latest:
    extends:
      file: docker-compose-build.yml
      service: dev
    image: muccg/logspout-logstash:latest
